create view V_CLIENTE as
SELECT CODIGO_CLIENTE,
       PRIMER_NOMBRE,
       SEGUNDO_NOMBRE,
       PRIMER_APELLIDO,
       SEGUNDO_APELLIDO,
       NIT,
       DIRECCION_CLIENTE,
       TELEFONO,
       ESTADOS.ESTADO CODIGO_ESTADO,
       CATALOGO_CATEGORIAS.NOMBRE_CATEGORIA                 CODIGO_CATEGORIA
FROM CLIENTE
         join ESTADOS ON CLIENTE.CODIGO_ESTADO = ESTADOs.CODIGO_ESTADO
         join CATALOGO_CATEGORIAS ON CLIENTE.CODIGO_CATEGORIA = CATALOGO_CATEGORIAS.CODIGO_CATEGORIA
/

