create view V_FACTURA as
SELECT VENTAS.CODIGO_VENTA,
       VENTAS.CODIGO_CLIENTE,
       VENTAS.ESTADO,
       FR.FECHA_EMISION,
       FR.TOTAL AS TOTAL,
       FR.FECHA_ACTUALIZACION AS FECHA_ACTUALIZACION,
       FR.TOTAL_PRODUCTOS,
       LISTAGG(INV.NOMBRE_PRODUCTO || '  CANTIDAD :' || DV.CANTIDAD, ' , ') WITHIN GROUP (ORDER BY INV.NOMBRE_PRODUCTO) AS DESCRIPCION_GENERAL
FROM VENTAS
         INNER JOIN DETALLE_VENTA DV ON VENTAS.CODIGO_VENTA = DV.CODIGO_VENTA
         INNER JOIN FACTURA_RESUMEN FR ON DV.CODIGO_VENTA = FR.CODIGO_VENTA
         INNER JOIN INVENTARIO INV ON INV.CODIGO_PRODUCTO = DV.CODIGO_PRODUCTO
group by VENTAS.CODIGO_VENTA, VENTAS.CODIGO_CLIENTE, VENTAS.ESTADO, FR.FECHA_EMISION, FR.TOTAL, FR.FECHA_ACTUALIZACION, FR.TOTAL_PRODUCTOS,FR.FECHA_EMISION, VENTAS.CODIGO_CLIENTE, VENTAS.ESTADO, VENTAS.CODIGO_VENTA, FR.TOTAL, FR.FECHA_ACTUALIZACION, FR.FECHA_EMISION, FR.TOTAL_PRODUCTOS
/

